defaultUncompletedIconColor = "#FFFFFF"
defaultUncompletedTitleColor = "#0489C1"
defaultCompletedIconColor = "#DBA213"
defaultCompletedTitleColor = "#DBA213"
doAdvancementsBackgroundFade = true
showDebugCoordinates = false
orderTabsAlphabetically = false
#Values below 50% might give odd results, use on own risk ;)
# Default: 100
# Range: 1 ~ 100
uiScaling = 100
#UI zoom steps are 0.1
# Default: 1.0
# Range: 0.4000000059604645 ~ 2.0
defaultZoom = 1.0
#Lists the criteria for partially completed advancements, e.g. the biomes required for 'Adventuring Time'
#    Off: Vanilla default
#    Default: List which criteria you have already obtained
#    Spoiler: Only reveal unobtained criteria
#    All: Show both obtained and unobtained criteria
criteriaDetail = "Default"
criteriaDetailRequiresShift = false
addInventoryButton = false
defaultDrawDirectLines = false
defaultHideLines = false
defaultCompletedLineColor = "#FFFFFF"
defaultUncompletedLineColor = "#FFFFFF"
onlyUseAboveAdvancementTabs = false
